name: Release to TestPyPI
  
on:
  push:
    tags:
     - "v*b*"
  workflow_dispatch: {}
  
jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
  
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
  
      - name: Install build tooling
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade build twine

      - name: Build sdist and wheel
        run: |
          rm -rf dist/
          python -m build
  
      - name: Twine check metadata
        run: python -m twine check dist/*
  
      - name: Upload to TestPyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TEST_PYPI_API_TOKEN }}
        run: python -m twine upload --non-interactive --repository-url https://test.pypi.org/legacy/ dist/*

